#pragma once

#define RGB_CONFIRMATION_BLINKING_TIME 1000 // 1 second
#define RGB_DISABLE_TIMEOUT 300000          // 5 minutes (5 * 60 * 1000ms)
#define RGB_DISABLE_WHEN_USB_SUSPENDED
#define DISABLE_FACTORY_KEYCHRON_HOOKS
